### ISSUE TITLE
Make pressure Plate that can detect 3 weights small, medium, large

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#12]
detects total weight of coins and dragon, or objects

**Comment by oleahv** [comment]
Can use mass for this. Pending values from the the different sizes.

**Comment by oleahv** [comment]
Using player name (SMALL, MEDIUM, LARGE) to seperate between the "weights". The design could use a rework depending on size(s) of the model(s).

**Comment by oleahv** [comment]
Add a visual indicator of size needed to activate the pressure plate. Image (see Discord chat)

**Comment by oleahv** [comment]
NOTE: The variable is not on the top layer of the object, and should be a correlation between event and image.
