### ISSUE TITLE
Make a fountain that can hold coins (should be main source of finding coins in a new room

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#16]
![image](https://user-images.githubusercontent.com/60709685/190627947-c14b6f84-7a91-4025-abad-1aafbb0d130c.png)

Maybe alla Mario 64 world?

**Comment by FredrikLonnemo** [comment]
Closing for now, Ideally want a more elegant way to cap/limit coins spawned (taking into account how many coins are in the scene and on the dragon) but it's not very important
