### ISSUE TITLE
Make a startup screen

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#19]

**Comment by ThomasMACHINE** [comment]
Added a simple start at Scenes/Thomas/StartMenu - Someone can pick this up if they want, otherwise I will do it over the weekend

**Comment by ThomasMACHINE** [comment]
## Implementation needed

### Press the button to deactivate the main panel and activate the LevelSelection (panel)
![image](https://user-images.githubusercontent.com/53544690/198499837-54eb27fa-d71b-41fb-bf05-7c4c38865c30.png)


### Make buttons load up scene (Maybe create a cool design and show multiple levels?)
![image](https://user-images.githubusercontent.com/53544690/198500068-981ae142-366c-415f-9b4e-43ff5acc66f5.png)

**Comment by ThomasMACHINE** [comment]
Functionality in place, but could possibly need some more content (Credits etc) in the future
