### ISSUE TITLE
Improve Crate implementation

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#34]
The crate has the following problems that need to be assessed:

- Should be able to pick up and interact with more than one crate per scene
- Crate should not spin out of control if it touches something
- Crate should "jump" with the dragon

Additionally, the crate should not be able to be used to perform an infinite jump portion (This would be a bug)

**Comment by Suilion** [comment]
You can now pick up all crates in a scene.

**Comment by Suilion** [comment]
Crate doesnt spin out of controll when touching other objects, but the jumping implementation is flawed. It works as long as the player does not rotate the camera while jumping.

**Comment by Suilion** [comment]
Waiting on issue #36 to get resolved to go back and look at this.

**Comment by oleahv** [comment]
Only the top layer of the crate object should be considered to be ground layer. See issue #37 .
