### ISSUE TITLE
Crate following you when you deevolve.

### ISSUE THREAD

**Issue by oleahv** [ThomasMACHINE/PennyWise#38]
Pick up the crate, evolve -> the crate gets dropped.
Deevolving again -> the crate tries to move into "picked-up" position.

**Comment by oleahv** [comment]
Could call the drop-crate mehtod when deevolving (if there is any deevolve available).

**Comment by Suilion** [comment]
Tried to reproduce this glitch, but wasnt able to. I did discover that the large dragons holder was a litle close, leading the box to be able to bump into the dragon while holding it, so I fixed that, but tried in multiple scenes to recreate what you descibed without being able to.
