### ISSUE TITLE
Make a gold golem that chases the dragon and steals its gold

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#44]
slime catches the big dragon: 
* eats gold
* turns it into medium dragon
* spits the dragon out

Slime catches the medium dragon:
*eats gold
* turns it into smal dragon
* spits the dragon out

Slime catches the smal dragon:
* eats whatever gold it has
* spits the dragon out

**Comment by ThomasMACHINE** [comment]
Currently needs a nicer hitbox and fix the base rotation of the object so that it looks in the proper direction

**Comment by ThomasMACHINE** [comment]
### Fixes Required
Fix gold golem walking + rotation

### Features
Animation that shows coin being eaten

**Comment by ThomasMACHINE** [comment]
https://streamable.com/90z1cf Animation looks cool

**Comment by ThomasMACHINE** [comment]
### Feature Request

If player has no money, reset level
If players money is lower than evolve threshold, devolve

**Comment by ThomasMACHINE** [comment]
Implemented in 2b8023f4d120e6d6313792aa8e91bfb78214d417
