### ISSUE TITLE
Camera should not pass through wall (or objects)

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#48]
We need to find a way so that the camera doesnt pass through walls/objects, its dissorienting, and can give players x-ray vision if done correctly.

**Comment by oleahv** [comment]
One solution is putting a collider on the camera to stop it from getting to close. Could be issues if something gets inbetween player and camera.

**Comment by Suilion** [comment]
Thomas:" Du kan sjekke om det er noe i posisjonen til kameraet, og hvis det er noe der så går zoomer den mer og mer inn til spilleren"

**Comment by Suilion** [comment]
reset scene skall ikke resette kamera

**Comment by ThomasMACHINE** [comment]
Can probably just add:

Physics.CheckSphere(model.position, randomRadius, ~playerMask)

to check for collisions between other objects and then increase the zoom if it is true
