### ISSUE TITLE
Smoother transition when evolving/deevolving.

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#49]
As it is now, when the dragon changes size, the camera imideatly jumps to the new position, which can be jarring. As well as the change from a smaller dragon to a larger dragon makes the dragon jump(?) a little. Thats the best way I can describe it.

**Comment by oleahv** [comment]
The "jump" (in y-axis) would be because the dragon model are spawning slightly above ground, to avoid clipping into it (and thus fall to the killzone).
