### ISSUE TITLE
Popup text explaining how to use abilities 

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#50]
fesk lv 1 should have box: press space while jumping to activate glide

**Comment by ThomasMACHINE** [comment]
Currently not implemented in any levels, could possibly add this to the player prefab so that it persists through levels

https://streamable.com/oikaxd

**Comment by ThomasMACHINE** [comment]
Everything needed for it should be implemented, The actual messages could be implemented along with #54
