### ISSUE TITLE
Evolve bugs

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#52]
- Make big dragon not able to pick up coins
- Make change so that if you deevolve to medium dragon and then to small dragon you cannot imideatly (due to bug) become medium again

**Comment by ThomasMACHINE** [comment]
What exactly is the bug? I assume this was because you could have an excess amount coins by picking them up as the large dragon.

As the first point is resolved the latter should be to so I will close the Issue.
