### ISSUE TITLE
Make intro slideshow

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#56]

**Comment by ThomasMACHINE** [comment]
# Requirements

1. We have the GIF, find out how to make the slideshow
2. Implement a voice over and play it at the same time
3. A nice uplifting sound track in the background!

**Comment by Suilion** [comment]
The intro is finished, uploading as MP4 here

https://user-images.githubusercontent.com/60709685/203977556-5d13ae68-4076-48c9-add9-7473d5d7dea7.mp4
