### ISSUE TITLE
Testing - Guards have a bug

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#61]
Guards ahve a bug where if you quickly roar as the large dragon in sucsession, the area of their field of view doesnt change back to the default color.

**Comment by ThomasMACHINE** [comment]
Could not replicate bug but saw some weird bug where if you:

Spam Roar -> wait for it to turn back -> Roar

The guard will only be scared for a very short time

**Comment by ThomasMACHINE** [comment]
Added a cooldown so that they cannot spam it and create concurrency issues (I dont want to debug that lol). It fixes the issue and also probably makes for better game design as the game would be to easy if they can just run down the game and spam L

**Comment by ThomasMACHINE** [comment]
I consider this issue completed, if you agree close this issue, if add Polish label and requested features

**Comment by oleahv** [comment]
LGTM!
