### ISSUE TITLE
Dragon, Sounds

### ISSUE THREAD

**Issue by ThomasMACHINE** [ThomasMACHINE/PennyWise#77]
## Implement Sounds for following Dragon Actions:

1. Roar
2. Walk
3. Jump
4. Glide?
5. Evolve
6. Devolve

**Comment by Suilion** [comment]
Yes glide should have a continious one so its easy to tell when its gliding, we got some feedback on that on the testing, i finished #69 just now, but havent added any sound to it.

**Comment by Suilion** [comment]
Only problem is that all sounds play on reload

**Comment by ThomasMACHINE** [comment]
Animations have the same problem, maybe its the same cause

**Comment by Suilion** [comment]
> Animations have the same problem, maybe its the same cause

The reason was this selection in inspector:
![image](https://user-images.githubusercontent.com/60709685/205318832-fb69232a-0271-46b2-a5e5-bbc82988943a.png)
