### ISSUE TITLE
Make it so the guard can only see a part of the circle and not all of it

### ISSUE THREAD

**Issue by Suilion** [ThomasMACHINE/PennyWise#8]
![image](https://user-images.githubusercontent.com/60709685/190626298-9b0a0074-d504-4dae-bf67-4816c9146387.png)

Similar to Sly Cooper

**Comment by oleahv** [comment]
Could split the circle object down, ignore parts of it or limit it in the code.

**Comment by oleahv** [comment]
The prefab needs to be adjusted before use. The playercontroller should reference only have one option in the scene (still need to set it) and the guardObject should reference the actual guardObject. (Not changing this while having several guard objects in a scene will cause the LOS check to be conducted based on the position to the original guard object).

**Comment by oleahv** [comment]
See commit b19b0158485ad5a3f89ed37919edcf29e2fca17d
